FROM node:12.16


RUN echo "deb http://ftp.de.debian.org/debian sid main" >> /etc/apt/sources.list && \
    apt-get -qqy update && \
    apt-get -qqy install pdf2htmlex poppler-utils && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app
EXPOSE 8080 3000
CMD npm install && npm run dev & cd front && npm install && npm run serve